### PR TITLE
simplified web structure

### PR DESCRIPTION
**Pull request by pallyjoel**
The new version now has only 3 pages. Blog, projects, data. with the contact information in the bottom footer.

### CODE REVIEW

**Comment by Ryan-J-Smith** [comment]
So I built this locally and I'm not sure I like the complete absence of a
landing page.  Steve, have you had a chance to view this yet?

**Comment by Ryan-J-Smith** [comment]
Also the site won't compile correctly without removing the "@" symbol in the _config.yml file.

**Comment by stephen-l-morgan** [comment]
Next iteration:  

1.  Make contact only the email.
2.  Move projects before data on nav bar.
3.  Put the paragraph from existing About page at the top of what is now called the Home page.  Remove first paragraph from the blog post.

**Comment by stephen-l-morgan** [comment]
But now I see that the "about" content in the light blue bar remains there when you go to the projects and data pages.  I liked having that bar say projects and data for those pages.  Is that possible, or does the template forbid it?

**Comment by stephen-l-morgan** [comment]
Let's also change the heading "Our Datasets" on the Data page to "Data Resources"

**Comment by stephen-l-morgan** [comment]
Let's hold off on me forking your fork now ... or whatever.  Here are some changes to make for now:
1.  Our Datasets to Data Resources (this one must have gotten lost in the theft!)
2.  Projects page:  remove the dummy demo2 project from the table.
3.  Then, let's edit the Signal 13 project page together, so that I can learn a bit more.

**Comment by stephen-l-morgan** [comment]
On Home page, left justify the "about" content in the banner.

On the Data page, in the table for the scanner files:  
(1) say how many 30 minute files are there (not just "several")
(2) put in a sentence, like on the projects, page linking to and crediting scanbaltimore

On Signal 13 page
(1) go try to better organize the soundcloud page as we discussed 
(2) change to "if" in "time fi available"
(3) "adn" not "and"
(4) consistent capitalizaiton of SoundCloud and scanbaltimore
(5) change "send it via email to us at [email address here] any thoughts or additional transcription.)" to "send your thoughts and additional transcription to us at BaltimoreCityDataLab@gmail.com."
(6) fix the link to the map from scanbaltimore in the first tip
(7) tip 3, put in a sensible link for scanbaltimore
(8) link to the map again in tip 4
(9) tip 4 "its" not "it's"

**Pull request merged**
